Repository wirecard/oxid-ee, pull requests merged in 2020-04, with the labels that each got.

#221 Add change release version GitHub action
  .github/workflows/change-release-version.yml
Labels: no-release, ready for approval

#222 Remove incompatible version and improve PayPal tests
  .bin/shop-releases.txt
  Dockerfile
  Tests/Acceptance/PaypalCheckoutTest.php
  Tests/Acceptance/inc/config.json
  Tests/Acceptance/inc/locators.json
  docker-compose.ci.yml
Labels: no-release

#206 Fix top order button for credit card
  out/js/wirecard_wdoxidee_credit_card_form.js
Labels: ready for review

#225 Change alipay xborder logo
  out/img/alipay.png
Labels: ready for merge

#223 Send order number if additional information is disabled
  Extend/Model/PaymentGateway.php
Labels: ready for merge

#229 Tpwdcee 5163 feature
  out/js/wirecard_wdoxidee_credit_card_form.js
Labels: ready for approval

#227 Fixed error with database vault new fields and missing request fields towards wpp
  Core/OxidEeEvents.php
  Model/PaymentMethod/CreditCardPaymentMethod.php
Labels: ready for testing

#230 Review on the threeds2 us
  Core/AccountInfoHelper.php
  Core/OxidEeEvents.php
  Core/RiskInfoHelper.php
  Core/Vault.php
  Model/PaymentMethod/CreditCardPaymentMethod.php
Labels: ready for review

#234 Fix code style issues
  Extend/Controller/OrderController.php
  Tests/Unit/Extend/Controller/OrderControllerTest.php
Labels: ready for review

#228 Add IO converter to composer json
  .gitignore
  Extend/Controller/OrderController.php
  Gemfile.lock
  composer.json
  composer.lock
Labels: ready for merge

#235 Added missing php version to the plugin version spec
  Core/Helper.php
Labels: ready for approval

#237 Check PR branch name validation
  .github/pr-labeler.yml
  .github/prlint.json
Labels: no-release, ready for review

#238 Add github action to validate travis file
  .github/workflows/validate-travis-file.yml
  .travis.yml
Labels: no-release

#233 Rc 1.3.0 minor
  .gitignore
  CHANGELOG.md
  Core/AccountHolderHelper.php
  Core/AccountInfoHelper.php
  Core/Helper.php
  Core/OxidEeEvents.php
  Core/RiskInfoHelper.php
  Core/ThreedsHelper.php
  Core/Vault.php
  Extend/Controller/OrderController.php
  Extend/Model/Order.php
  Extend/Model/PaymentGateway.php
  Gemfile.lock
  Model/PaymentMethod/CreditCardPaymentMethod.php
  README.md
  SHOPVERSIONS
  Tests/Integration/Core/VaultTest.php
  Tests/Unit/Core/AccountHolderHelperTest.php
  Tests/Unit/Core/AccountInfoHelperTest.php
  Tests/Unit/Core/RiskInfoHelperTest.php
  Tests/Unit/Core/ThreedsHelperTest.php
  Tests/Unit/Extend/Controller/OrderControllerTest.php
  Tests/Unit/Extend/Model/PaymentGatewayTest.php
  Tests/Unit/Extend/Model/PaymentTest.php
  Tests/Unit/Model/CreditCardPaymentMethodTest.php
  composer.json
  composer.lock
  default_payment_config.xml
  metadata.php
  out/img/alipay.png
  out/js/wirecard_wdoxidee_credit_card_form.js
  views/admin/de/module_de_lang.php
  views/admin/en/module_en_lang.php
Labels: minor

#240 Use Wirecard GitHub actions and expand PR labeler
  .github/pr-labeler.yml
  .github/workflows/change-release-version.yml
  .github/workflows/create_release.yml
Labels: no-release
